# Generated by Django 4.2.5 on 2023-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_coalstock_siding_coalstock_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='railway',
            name='capacity',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
